server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
build:
  version: "1.0"

contact:
  message: "Welcome to esebray account service default from github"
  contact_info:
    name: "Sunday Esebre"
    email: "sunday.esebre@company.com"
  onCallSupport:
    - 333333333
    - 22222222
