server:
  port: 8090
spring:
  application:
    name: "accounts"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: "rabbit"
    port: 5672
    username: "guest"
    password: "guest"

  config:
    import: "optional:configserver:http://config-server:8071"
management:
  endpoints:
    web:
      exposure:

        include: "*"
build:
  version: "1.0"

contact:
  message: "Welcome to esebray account service default from github webhook"
  contact_info:
    name: "Sunday Esebre"
    email: "sunday.esebre@company.com"
  onCallSupport:
    - 333333333
    - 22222222

