spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "2.0"

contact:
  message: "Welcome to esebray account service prod from github"
  contactInfo:
    name: "Sunday Esebre production"
    email: "prod@company.com"
  onCallSupport:
    - 444444
    - 55555


