build:
  version: "1.0.0"
server:
  port: 8090
spring:
  application:
    name: "loans"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: "qa"
  config:
    import: "optional:configserver:http://configserver:8071"
  rabbitmq:
    host: "rabbit"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"

contact:
  message: "Welcome to esebray loan service default from github"
  contact_info:
    name: "Daniel Esebre loan"
    email: "{cipher}bc3d247f925c706c8175c067fa1717e0042978f1bc84916761e715579216415aba7bc67589c21712e02ce9a759875b0b"
  onCallSupport:
    - 77
    - 77
